version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/Express/videos:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/Express/videos
    command: ["-limit", "6"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4444/wd/hub/status || exit 1
      interval: 10s
      timeout: 10s
      retries: 3

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      selenoid:
        condition: service_healthy

  allure:
    image: "frankescobar/allure-docker-service:2.13.6"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/Express/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports
      - ${PWD}/Express/allure-config/custom-logo-plugin:/allure/plugins/custom-logo-plugin
      - ${PWD}/Express/allure-config/config:/allure/config

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"